##
## Configuration for librarian-puppet
## Lists the modules we depend upon.
##

forge "http://forge.puppetlabs.com"

# mod "puppetlabs/apache"
mod "puppetlabs/nginx"
mod "puppetlabs/postgresql"

mod "example42/puppi"
mod "example42/monitor"

mod "solr",
   :git => "https://github.com/example42/puppet-solr"

mod "python",
   :git => "https://github.com/stankevich/puppet-python"

mod "ckan",
   :path => "/vagrant/puppet/modules/ckan"
